### ISSUE TITLE
Invalid stream

### ISSUE THREAD

**Issue by PTgamer** [lorf/csr-spi-ftdi#13]
Hello!
So i was flowing a guide to do this hack to a ps2 controller i did everything but now i get an error saying "invalid stream select a SPI transport to attempt reconnect"
Can someone help me?  
my hc-05 is powered by an arduino mega and i have 100 ohms resistors from the DTR,R1,RTS,DSR to the hc-05

i have windows 10 is that a problem?
![untitled](https://cloud.githubusercontent.com/assets/20358046/20487051/dd0ac6e2-aff9-11e6-9249-d5cd23e74444.png)

**Comment by PTgamer** [comment]
I just tried on the XP and i get the same error

**Comment by lorf** [comment]
Hi! What version of Blue Suite You use?

**Comment by PTgamer** [comment]
Hello again,
i used the 2.4 and the new one the 2.6.4

**Comment by PTgamer** [comment]
and i used this guide 
https://mitxela.com/projects/bluetooth_hid_gamepad

**Comment by PTgamer** [comment]
Hello!
So i had another chip and i decide to try it and it worked  probably the other chip was bad i don't know 
but thx for the quick response
