### ISSUE TITLE
CSR8645 dead by 3.3V?

### ISSUE THREAD

**Issue by adnion** [lorf/csr-spi-ftdi#21]
I wanted to program my CSR8645 using a FT232RL chip with 3.3V.
I didn't manage to get a connection ("Unable to start read (invalid control data)").
However the red leds stopped working. I don't know why.

Do you know how to check if the module is alive or dead?

Thanks for your ideas!

**Comment by gamelaster** [comment]
I communicating right now with CSR8635 with 3.3V and it's fine

**Comment by adnion** [comment]
Solved. I accidentally made a short circuit when soldering the programming cables.
