### ISSUE TITLE
CH341A Support?

### ISSUE THREAD

**Issue by ghost** [lorf/csr-spi-ftdi#52]
Hello! This question is a bit off topic, but I was curious to know if the same procedure for the using BlueSuit with FT232RL can also be done with the CH341A chip too? The CH341A breakout board that I'm using can be found [here](https://images-na.ssl-images-amazon.com/images/I/613w2Zv13HL._AC_SL1000_.jpg) . Both the CH341A and FT232RL pinouts appear to be similar. I have all of the drivers and software required for the operation of the CH341A and I have BlueSuit 2.6.6. I just don't know what to do next. I am trying to connect to a CSR8630 chip to the CH341A board via USB-SPI interface. I'd appreciate it if anyone could help me out here! ;)

**Comment by lorf** [comment]
Hi! There is a port to ch341a: https://github.com/puppywang/csr-spi-ch341. Not tried it though.
